### ISSUE TITLE
Problems of action wall

### ISSUE THREAD

**Issue by colorjam** [mit-han-lab/amc-release#5]
Thank you for sharing the code. 

1. In the env/channel_pruning_env.py, line 282 and 285, found conflicts between code and comments:
```
if i == self.cur_ind - 1:  # TODO: add other member in the set
  this_comp += flop * self.strategy_dict[idx][0]
  # add buffer (but not influenced by ratio)
  other_comp += buffer_flop * self.strategy_dict[idx][0]
elif i == self.cur_ind:
  this_comp += flop * self.strategy_dict[idx][1]
  # also add buffer here (influenced by ratio)
  this_comp += buffer_flop
```
2. Why you only consider input reduction of buffer flops?

**Comment by tonylins** [comment]
Hi,

Thanks for the feedback.

1. I will look into the issue to see if there is any bug.

2. In MobileNet example, buffer ops usually refer to depthwise convolution. Therefore, you should only consider the input/output channel reduction once (they are the same).

**Comment by tonylins** [comment]
After reading the code carefully (it has been around one year since I wrote the code), the code itself is correct, but the comment might be confusing.

In the code, when pruning layer `idx`'s input channels, I used `this_comp` to indicate the computation that will be influenced by the pruning rate of layer `idx`'s input, while using `other_comp` to indicate the computation that is irrelevant to the pruning rate. However, to implement the action all, the value in `this_comp` is actually *before* applying the pruning ratio.

For each layer, if the pruning rate of input is `a1`, the pruning rate of output is `a2`, then the computation after pruning would be `computation * a1 * a2 + buffer_computation * a1` in MobileNet setting, where "buffer" refers to the depth-wise layer before the point-wise layer. The computation of the depth-wise layer is only relevant to the input pruning rate of the following point-wise conv.

So for the layer before the current pruned layer (`i == self.cur_ind - 1`), the buffer computation is irrelevant. Therefore, we directly multiply its input pruned ratio. While for the current layer, the buffer computation is relevant, so we put it in `this_comp` and did not multiply `a1` until Line 292 where we finally multiplied it by `a1` (i.e., `action`).

This could be a little bit indirect to understand. I will close the issue for now. Feel free to reopen it if you have further questions.

**Comment by colorjam** [comment]
Thank you for the quick reply. 

Actually, I am confused about Line 292 since `self.expected_min_preserve` never been used after this line, so what is  `expected_min_preserve` mean?

In paper, the algorithm uses the maximum sparsity ratio to multiply the later layers, but you use the `strategy_dict`(current sparsity ratio) to compute the action_t, does implementation detail different from the paper?
